POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMkBhYjEyLm5ldCIsImlkIjoxLCJpYXQiOjE3MjYxNDI0MjR9.t4FuI3qNqKTS24nPuFsvHajFT3DID9UXLRf47kSgm34

  {
    "author": "Jmm",
    "url": "/blog3",
    "title": "Test",
    "likes": 7,
    "year": 1997
  }